version: '3.3'
services:
    server:
      build:
        context: ./
        dockerfile: ./server/Dockerfile
        args:
          DEBUG: 'True'
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./server:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DEBUG: 'True'
        DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'

    db:
      image: postgres:12.4-alpine
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: swagger-ui
      ports:
        - "8001:8080"
      volumes:
        - ./swagger:/usr/share/nginx/html/swagger
      environment:
        API_URL: swagger/api.json
